In [1]:
import numpy as npp

In [2]:
npp.__version__

'1.24.3'

In [3]:
import pandas as pp

In [4]:
pp.__version__

'1.5.3'

In [6]:
arr=npp.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr2=npp.array([[1,2],[3,4]])
arr2

array([[1, 2],
       [3, 4]])

In [9]:
del npp

In [10]:
arr2=npp.array([[1,2],[3,4]])
arr2

NameError: name 'npp' is not defined

In [11]:
npp.__version__

NameError: name 'npp' is not defined

In [12]:
import numpy as np

In [13]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
#a 4d array has 4 parameters where
#a--> no. of blocks
#b-->in each block how many rows
#c-->in each row how many cols
#d-->in each col how many elements
array4d=np.array([
                [
                    [
                        [1,2],
                        [3,4],
                        [5,6]
                    ],
                    [
                        [7,8],
                        [9,10],
                        [11,12]
                    ],
                    [
                        [13,14],
                        [15,16],
                        [17,18]
                    ]
                ],
                [
                    [
                        [19,20],
                        [21,22],
                        [23,24]
                    ],
                    [
                        [25,26],
                        [27,28],
                        [29,30]
                    ],
                    [
                        [31,32],
                        [33,34],
                        [35,36]
                    ]
                ]
])

In [18]:
array4d

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]],


       [[[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])